name: pip_services3_mongodb
version: 1.0.3
author: Sergey Seroukhov <seroukhov@gmail.com>
description: This framework is part of the [Pip.Services](https://github.com/pip-services/pip-services) project. It contains the following MongoDB components.
homepage: https://github.com/pip-services3-dart/pip-services3-messaging-dart

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  pip_services3_commons: ">=1.0.4 <2.0.0"
  pip_services3_components: ">=1.0.2 <2.0.0"
  pip_services3_data: ">=1.0.0 <2.0.0"
  mongo_dart: "^0.4.0"
  mongo_dart_query: "^0.4.1"

 
dev_dependencies:
  test: '>=1.14.2 <2.0.0'